FROM centos:latest
MAINTAINER keshav Sharma <datageeks84@gmail.com>
ENV PATH=”/root/miniconda3/bin:${PATH}”
ARG "${path}"
RUN yum -y update \
    && yum -y install curl bzip2 \
    && curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh  \
    && bash /tmp/miniconda.sh -bfp /usr/local/ \
    && rm -rf /tmp/miniconda.sh \
    && conda install  -y python=3 \
    && conda update conda\
    && conda clean --all --yes \
    && rpm -e  --nodeps curl bzip2 \
    && yum clean all
RUN conda install tensorflow -y
RUN conda install keras -y
RUN conda install pillow -y
RUN conda install smtplib -y
RUN mkdir /root/MODEL/
VOLUME /root/MODEL/
COPY cat and dog images /root/MODEL/cat and dog images
COPY Model.py /root/MODEL
WORKDIR /root/MODEL/

CMD [“bin/bash”]
CMD [“python3”,”Model.py”]
